feature/task-552-edit-plugin
getpingback/embed pull request #1
Opened 2021-06-18 21:02 UTC by matheusslg

2021-06-21 13:32 UTC, fabionofre commented on src/index.js
> +  formatElement(obj, el) {
What do you think about renaming this function for something related with attributes?

2021-06-21 13:41 UTC, pepeladeira reviewed
Wonderful?

2021-06-21 13:41 UTC, pepeladeira commented on src/index.js
> +    };
how about `http`?

2021-06-21 14:10 UTC, matheusslg commented on src/index.js
> +    };
Only HTTPS embeds will be accepted, for security reasons.

2021-06-21 14:57 UTC, gabrielmoterani requested changes
I think we should have a few trusted services with the pattens. Any other link that user wants to handle should be handle in linktool (and if linktool detect those patterns should convert to embed)

2021-06-21 14:57 UTC, gabrielmoterani commented on src/services.js
> +    regex: /^https?:\/\/.*/i
I don't get it. Why we don't have patterns anymore?
This may not work as expected. If I want to paste a link of another Pingback post for exemple. This would go to Iframely? We have our own Linktool. Iframely should only solve embeds that we consider safe to the application. I don't think its a great idea to accept iframes from all services that iframely trusts. And I don't think its a good Idea quitting our own link tool to use their. That would make us very dependent of their service.

2021-06-21 15:07 UTC, danielsalles commented on src/services.js
> +    regex: /^https?:\/\/.*/i
My 50 cents.
Does link tool work as an embed tool? It seems strange to me to have two parts of the site to embed. In my view the link tool should work as a hyperlink and not embed.

2021-06-23 17:11 UTC, matheusslg commented
Moved to https://github.com/getpingback/pb-link/commit/ca0a4a7ddaf4087eeabc419a96cb4a3df8c1b32d

2021-06-23 17:11 UTC, closed without merging